[input]
  file            = "testgr2.dump"
  coord_type      = "unwrapped"
  start_frame     = 0
  end_frame       = 3999
  frame_interval  = 1

[output]
  path            = "output"

[properties]
  type = "unknown"
  units = ""
  density = 1
  dt = 0.1

[analysis]
  
  [analysis.msd]
    enabled     = false
    max_lag     = 2000
    groups      = [["C"], ["O"], ["O", "C"]]
    plot_format = "svg"
    curves = [
      [  # Plot 1
        { types = ["C"], label = "C" },
        { types = ["2"], label = "2" }
      ],
      [  # Plot 2
        { types = ["3"], label = "3" }
      ]
    ]

  [analysis.rdf]
    enabled     = true
    num_bins    = 200
    r_max       = 5
    pairs       = [["3", "3"]]
    plot_format = "svg"
    curves = [
      [  # Plot 1
        { types = ["1", "2"], label = "1-2" },
        { types = ["1"], label = "1" }
      ],
      [  # Plot 2
        { types = ["1", "2"], label = "1-2" }
      ]
    ]

  [analysis.mfpt]
    enabled = false
    dt = 0.05
    dr = 0.01
    r_max = 4
    plot_dofr = true
    plot_format = "svg"

  [analysis.correlations]
    enabled = false
    plot_format = "png"
    
    # Built-in correlation functions
    builtin = ["vacf"]

    # Generic pairwise correlations
    custom = [
      { name = "some_corr", files = ["something_a.dat", "something_b.dat"]},#, columns = [2, 2] },
    ]
