[input]
  file            = "testgr2.dump"
  coord_type      = "unwrapped"
  start_frame     = 0
  end_frame       = 3999
  frame_interval  = 1

[output]
  path            = "output"

[properties]
  dt = 0.1

[analysis]
  
  [analysis.msd]
    enabled     = true
    max_lag     = 2000
    groups      = [["1"]]
    plot_format = "svg"
    curves = [
      # [  # Plot 1
      #   { types = ["2"], label = "2" },
      #   #{ types = ["3"], label = "3" },
      # ],
      [  # Plot 2
        { types = ["1"], label = "1" }
      ]
    ]

  [analysis.rdf]
    enabled     = false
    num_bins    = 200
    r_max       = 5
    pairs       = [["3", "3"], ["1", "2"]]
    plot_format = "svg"
    curves = [
      [  # Plot 1
        { types = ["1", "2"], label = "1-2" },
        { types = ["3", "3"], label = "3-3" }
      ],
      [  # Plot 2
        { types = ["1", "2"], label = "1-2" }
      ]
    ]

  [analysis.mfpt]
    enabled = false
    dt = 0.05
    dr = 0.01
    r_max = 4
    plot_dofr = true
    plot_format = "svg"

  [analysis.correlations]
    enabled = false
    plot_format = "svg"
    
    # Built-in correlation functions
    builtin = ["vacf"]

    # Generic pairwise correlations
    # custom = [
    #   { name = "sine_corr", files = ["sine_wave.dat"], columns = [2] },
    # ]
